name: NestJS CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}'
          SQUASH_HISTORY: true
          CLEAR_GLOBS_FILE: '.github/workflows/.deploy-ignore'

  hook:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Webhook Action
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.MAIN_SERVICE_WEBHOOK_URL }}

      # - name: Invoke deployment hook
      #   uses: distributhor/workflow-webhook@v2
      #   env:
      #     webhook_url: ${{ secrets.WAKE_SERVICE_WEBHOOK_URL }}
      #     webhook_secret: "test"

      - name: Webhook Action
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.WAKE_SERVICE_WEBHOOK_URL }}
